name: Generate JSON for mofish-icon

on:
  push:
    paths:
      - 'Collection/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

        - name: Generate collection.json
        id: generate-collection
        run: |
          REPO_OWNER=$(echo s0lnce/mofish-icon | cut -d '/' -f 1)
          REPO_NAME=$(echo s0lnce/mofish-icon | cut -d '/' -f 2)
          declare -a icon_elements
          for file in Collection/*; do
            if [ -f "$file" ]; then
              FILENAME=$(basename "$file")
              # 去除 .png 后缀
              NAME="${FILENAME%.png}"
              URL="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/main/Collection/${FILENAME}"
              icon_elements+=("{\"name\": \"${NAME}\", \"url\": \"${URL}\"}")
            fi
          done
          IFS=','
          ICON_ARRAY="[${icon_elements[*]}]"
          JSON_CONTENT="{\"name\": \"solnce摸鱼项目-icon\", \"description\": \"solnce\", \"icons\": $ICON_ARRAY}"
          echo "${JSON_CONTENT}" | jq '.' > collection.json
          # 对 JSON 内容进行转义
          ESCAPED_JSON=$(jq -Rs '.' collection.json)
          echo "collection_json_content=$ESCAPED_JSON" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update iconcollection.json with new files"
          file_pattern: iconcollection.json