name: Generate JSON for mofish-icon

on:
  push:
    paths:
      - 'glass/**'
      - 'glass3/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate glass.json
        id: generate-glass
        run: |
          REPO_OWNER=$(echo s0lnce/mofish-icon | cut -d '/' -f 1)
          REPO_NAME=$(echo s0lnce/mofish-icon | cut -d '/' -f 2)
          declare -a icon_elements
          for file in glass/*; do
            if [ -f "$file" ]; then
              FILENAME=$(basename "$file")
              # 去除 .png 后缀
              NAME="${FILENAME%.png}"
              URL="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/main/glass/${FILENAME}"
              icon_elements+=("{\"name\": \"${NAME}\", \"url\": \"${URL}\"}")
            fi
          done
          IFS=','
          ICON_ARRAY="[${icon_elements[*]}]"
          JSON_CONTENT="{\"name\": \"Icon\", \"description\": \"solnce\", \"icons\": $ICON_ARRAY}"
          echo "${JSON_CONTENT}" | jq '.' > glass.json
          # 对 JSON 内容进行转义
          ESCAPED_JSON=$(jq -Rs '.' glass.json)
          echo "glass_json_content=$ESCAPED_JSON" >> $GITHUB_OUTPUT

      - name: Generate glass3.json
        id: generate-glass3
        run: |
          REPO_OWNER=$(echo s0lnce/mofish-icon | cut -d '/' -f 1)
          REPO_NAME=$(echo s0lnce/mofish-icon | cut -d '/' -f 2)
          declare -a icon_elements
          for file in glass3/*; do
            if [ -f "$file" ]; then
              FILENAME=$(basename "$file")
              # 去除 .png 后缀
              NAME="${FILENAME%.png}"
              URL="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/main/glass3/${FILENAME}"
              icon_elements+=("{\"name\": \"${NAME}\", \"url\": \"${URL}\"}")
            fi
          done
          IFS=','
          ICON_ARRAY="[${icon_elements[*]}]"
          JSON_CONTENT="{\"name\": \"solnce摸鱼项目-icon\", \"description\": \"solnce\", \"icons\": $ICON_ARRAY}"
          echo "${JSON_CONTENT}" | jq '.' > glass3.json
          # 对 JSON 内容进行转义
          ESCAPED_JSON=$(jq -Rs '.' glass3.json)
          echo "glass3_json_content=$ESCAPED_JSON" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update glass.json and glass3.json with new files"
          file_pattern: glass.json glass3.json    
