name: Generate JSON for combined.json

on:
  push:
    paths:
      - 'surge/glass/**'
      - 'surge/glass3/**'
      - 'surge/pure/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate combined JSON
        id: generate-combined
        run: |
          REPO_OWNER=$(echo s0lnce/mofish-icon | cut -d '/' -f 1)
          REPO_NAME=$(echo s0lnce/mofish-icon | cut -d '/' -f 2)
          declare -a icon_elements
          
          # Process glass folder
          for file in surge/glass/*; do
            if [ -f "$file" ]; then
              FILENAME=$(basename "$file")
              NAME="${FILENAME%.png}"
              URL="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/main/surge/glass/${FILENAME}"
              icon_elements+=("{\"name\": \"${NAME}\", \"url\": \"${URL}\"}")
            fi
          done
          # Process glass3 folder
          for file in surge/glass3/*; do
            if [ -f "$file" ]; then
              FILENAME=$(basename "$file")
              NAME="${FILENAME%.png}"
              URL="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/main/surge/glass3/${FILENAME}"
              icon_elements+=("{\"name\": \"${NAME}\", \"url\": \"${URL}\"}")
            fi
          done

          # Process pure folder
          for file in surge/pure/*; do
            if [ -f "$file" ]; then
              FILENAME=$(basename "$file")
              NAME="${FILENAME%.png}"
              URL="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/main/surge/pure/${FILENAME}"
              icon_elements+=("{\"name\": \"${NAME}\", \"url\": \"${URL}\"}")
            fi
          done

          IFS=','
          ICON_ARRAY="[${icon_elements[*]}]"
          JSON_CONTENT="{\"name\": \"solnce摸鱼项目-icon\", \"description\": \"solnce\", \"icons\": $ICON_ARRAY}"
          echo "${JSON_CONTENT}" | jq '.' > combined.json
          ESCAPED_JSON=$(jq -Rs '.' combined.json)
          echo "combined_json_content=$ESCAPED_JSON" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update combined.json with new files"
          file_pattern: combined.json   